//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCSV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jos_download
    {
        public int ID { get; set; }
        public string FileName { get; set; }
        public string FilePath { get; set; }
        public string FileType { get; set; }
        public string Year { get; set; }
        public Nullable<decimal> Volumn { get; set; }
        public Nullable<long> updated_by { get; set; }
        public Nullable<System.DateTime> updated_time { get; set; }
        public Nullable<short> Status { get; set; }
    }
}
