//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCSV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jos_newsfeeds
    {
        public int catid { get; set; }
        public int id { get; set; }
        public string name { get; set; }
        public string alias { get; set; }
        public string link { get; set; }
        public string filename { get; set; }
        public short published { get; set; }
        public long numarticles { get; set; }
        public long cache_time { get; set; }
        public byte checked_out { get; set; }
        public System.DateTime checked_out_time { get; set; }
        public int ordering { get; set; }
        public short rtl { get; set; }
    }
}
