//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCSV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jos_menu_link_types
    {
        public long id { get; set; }
        public long id_menu { get; set; }
        public int id_category { get; set; }
        public Nullable<int> id_type_of_page { get; set; }
        public Nullable<int> id_content { get; set; }
    }
}
