//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCSV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jos_comment
    {
        public int ID { get; set; }
        public int content_id { get; set; }
        public string CommentContent { get; set; }
        public string SenderName { get; set; }
        public string SenderEmail { get; set; }
        public Nullable<System.DateTime> SentDate { get; set; }
        public Nullable<System.DateTime> LastEdited { get; set; }
        public Nullable<short> Status { get; set; }
    }
}
