//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCSV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jos_p_address
    {
        public decimal id { get; set; }
        public string title { get; set; }
        public long parent { get; set; }
        public long price { get; set; }
        public int ordering { get; set; }
        public short published { get; set; }
    }
}
