//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCSV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jos_messages
    {
        public long message_id { get; set; }
        public long user_id_from { get; set; }
        public long user_id_to { get; set; }
        public long folder_id { get; set; }
        public System.DateTime date_time { get; set; }
        public int state { get; set; }
        public long priority { get; set; }
        public string subject { get; set; }
        public string message { get; set; }
    }
}
