//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCSV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jos_jf_content
    {
        public long id { get; set; }
        public int language_id { get; set; }
        public int reference_id { get; set; }
        public string reference_table { get; set; }
        public string reference_field { get; set; }
        public string value { get; set; }
        public string original_value { get; set; }
        public string original_text { get; set; }
        public System.DateTime modified { get; set; }
        public long modified_by { get; set; }
        public byte published { get; set; }
    }
}
