//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCSV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jos_sef_sm_menu
    {
        public int menu_id { get; set; }
        public int published { get; set; }
        public int integrator { get; set; }
        public string integrator_id { get; set; }
        public int ordering { get; set; }
        public string @params { get; set; }
        public int ping_enabled { get; set; }
    }
}
