//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCSV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jos_links
    {
        public int id { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public Nullable<long> created_by { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public Nullable<long> modified_by { get; set; }
        public string name { get; set; }
        public string link { get; set; }
        public string description { get; set; }
        public int order { get; set; }
        public string image { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public string fax { get; set; }
        public string representative { get; set; }
        public int lang_id { get; set; }
        public byte published { get; set; }
    }
}
