//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCSV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jos_banner
    {
        public int bid { get; set; }
        public int cid { get; set; }
        public string type { get; set; }
        public string name { get; set; }
        public string alias { get; set; }
        public int imptotal { get; set; }
        public int impmade { get; set; }
        public int clicks { get; set; }
        public string imageurl { get; set; }
        public string clickurl { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public short showBanner { get; set; }
        public short checked_out { get; set; }
        public System.DateTime checked_out_time { get; set; }
        public string editor { get; set; }
        public string custombannercode { get; set; }
        public long catid { get; set; }
        public string description { get; set; }
        public byte sticky { get; set; }
        public int ordering { get; set; }
        public System.DateTime publish_up { get; set; }
        public System.DateTime publish_down { get; set; }
        public string tags { get; set; }
        public string @params { get; set; }
    }
}
