//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCSV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jos_p_order
    {
        public long id { get; set; }
        public string name { get; set; }
        public string datecreated { get; set; }
        public string timecreated { get; set; }
        public string datedelivery { get; set; }
        public string timedelivery { get; set; }
        public long price { get; set; }
        public string content { get; set; }
        public short published { get; set; }
        public long dateupdated { get; set; }
        public string username { get; set; }
        public float downbouns { get; set; }
        public string phuongthuc { get; set; }
    }
}
