//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCSV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jos_sef_sm_cache_items
    {
        public int id { get; set; }
        public int ordering { get; set; }
        public string name { get; set; }
        public string link { get; set; }
        public string image { get; set; }
        public string icon_path { get; set; }
        public int level { get; set; }
        public string lastmod { get; set; }
        public string changefreq { get; set; }
        public string priority { get; set; }
        public string description { get; set; }
    }
}
