//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCSV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jos_sef_sm_pingback
    {
        public int id { get; set; }
        public string ping_host { get; set; }
        public System.DateTime last_ping_date { get; set; }
        public int log_position { get; set; }
    }
}
