//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCSV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jos_xmap_sitemap
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> expand_category { get; set; }
        public Nullable<int> expand_section { get; set; }
        public Nullable<int> show_menutitle { get; set; }
        public Nullable<int> columns { get; set; }
        public Nullable<int> exlinks { get; set; }
        public string ext_image { get; set; }
        public string menus { get; set; }
        public string exclmenus { get; set; }
        public Nullable<int> includelink { get; set; }
        public Nullable<int> usecache { get; set; }
        public Nullable<int> cachelifetime { get; set; }
        public string classname { get; set; }
        public Nullable<int> count_xml { get; set; }
        public Nullable<int> count_html { get; set; }
        public Nullable<int> views_xml { get; set; }
        public Nullable<int> views_html { get; set; }
        public Nullable<int> lastvisit_xml { get; set; }
        public Nullable<int> lastvisit_html { get; set; }
        public string excluded_items { get; set; }
        public Nullable<int> compress_xml { get; set; }
    }
}
