//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCSV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jos_weblinks
    {
        public long id { get; set; }
        public int catid { get; set; }
        public int sid { get; set; }
        public string title { get; set; }
        public string alias { get; set; }
        public string url { get; set; }
        public string description { get; set; }
        public System.DateTime date { get; set; }
        public int hits { get; set; }
        public short published { get; set; }
        public int checked_out { get; set; }
        public System.DateTime checked_out_time { get; set; }
        public int ordering { get; set; }
        public short archived { get; set; }
        public short approved { get; set; }
        public string @params { get; set; }
    }
}
