//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCSV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jos_p_product
    {
        public long id { get; set; }
        public string title { get; set; }
        public string alias { get; set; }
        public string code { get; set; }
        public Nullable<long> price { get; set; }
        public float decrease { get; set; }
        public string note { get; set; }
        public string detail { get; set; }
        public short published { get; set; }
        public short isnew { get; set; }
        public short isgift { get; set; }
        public short status { get; set; }
        public long category { get; set; }
        public string image { get; set; }
        public int itemid { get; set; }
        public Nullable<long> dateupdated { get; set; }
        public string convert_title { get; set; }
        public string convert_note { get; set; }
        public string convert_detail { get; set; }
        public long ordering { get; set; }
        public string title_en { get; set; }
        public string note_en { get; set; }
        public string detail_en { get; set; }
        public string currency { get; set; }
        public string currency_en { get; set; }
        public long price_en { get; set; }
        public string categoryLinkID { get; set; }
    }
}
