//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCSV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jos_polls
    {
        public long id { get; set; }
        public string title { get; set; }
        public string alias { get; set; }
        public int voters { get; set; }
        public int checked_out { get; set; }
        public System.DateTime checked_out_time { get; set; }
        public short published { get; set; }
        public int access { get; set; }
        public int lag { get; set; }
    }
}
