//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCSV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jos_core_acl_aro
    {
        public int id { get; set; }
        public string section_value { get; set; }
        public string value { get; set; }
        public int order_value { get; set; }
        public string name { get; set; }
        public int hidden { get; set; }
    }
}
