//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCSV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jos_sef_sm_cache
    {
        public int id { get; set; }
        public int menu_id { get; set; }
        public string maptype { get; set; }
        public string lang { get; set; }
        public int gid { get; set; }
        public System.DateTime lastmod { get; set; }
        public int items { get; set; }
    }
}
