//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCSV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jos_components
    {
        public int id { get; set; }
        public string name { get; set; }
        public string link { get; set; }
        public long menuid { get; set; }
        public long parent { get; set; }
        public string admin_menu_link { get; set; }
        public string admin_menu_alt { get; set; }
        public string option { get; set; }
        public int ordering { get; set; }
        public string admin_menu_img { get; set; }
        public short iscore { get; set; }
        public string @params { get; set; }
        public short enabled { get; set; }
    }
}
