//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCSV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jos_sef_sm_pingback_menu
    {
        public int menu_id { get; set; }
        public int pingback_id { get; set; }
        public System.DateTime last_date { get; set; }
    }
}
