//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCSV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jos_session
    {
        public string username { get; set; }
        public string time { get; set; }
        public string session_id { get; set; }
        public Nullable<short> guest { get; set; }
        public Nullable<int> userid { get; set; }
        public string usertype { get; set; }
        public byte gid { get; set; }
        public byte client_id { get; set; }
        public string data { get; set; }
    }
}
