//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCSV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jos_content_rating
    {
        public int content_id { get; set; }
        public long rating_sum { get; set; }
        public long rating_count { get; set; }
        public string lastip { get; set; }
    }
}
