//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCSV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jos_sections
    {
        public int id { get; set; }
        public int lang_id { get; set; }
        public string title { get; set; }
        public string name { get; set; }
        public string alias { get; set; }
        public string image { get; set; }
        public string scope { get; set; }
        public string image_position { get; set; }
        public string description { get; set; }
        public short published { get; set; }
        public long checked_out { get; set; }
        public System.DateTime checked_out_time { get; set; }
        public int ordering { get; set; }
        public byte access { get; set; }
        public int count { get; set; }
        public string @params { get; set; }
    }
}
