//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCSV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jos_jf_languages_ext
    {
        public int lang_id { get; set; }
        public string image_ext { get; set; }
        public string fallback_code { get; set; }
        public string @params { get; set; }
        public int ordering { get; set; }
    }
}
