//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCSV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jos_awb_users
    {
        public int id { get; set; }
        public Nullable<int> id_user_type { get; set; }
        public string user_name { get; set; }
        public string user_passwd { get; set; }
        public string user_code { get; set; }
        public string company_name { get; set; }
        public string company_address { get; set; }
        public string phone { get; set; }
        public string fax { get; set; }
        public short status { get; set; }
    }
}
