//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCSV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jos_functions
    {
        public int id { get; set; }
        public long id_parent { get; set; }
        public string name { get; set; }
        public string link { get; set; }
        public short published { get; set; }
        public Nullable<int> ordering { get; set; }
        public byte access { get; set; }
    }
}
