//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCSV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jos_menu
    {
        public int id { get; set; }
        public Nullable<int> id_menutype { get; set; }
        public string menutype { get; set; }
        public string name { get; set; }
        public string alias { get; set; }
        public string link { get; set; }
        public string type { get; set; }
        public bool published { get; set; }
        public long parent { get; set; }
        public long componentid { get; set; }
        public Nullable<int> sublevel { get; set; }
        public Nullable<int> ordering { get; set; }
        public long checked_out { get; set; }
        public System.DateTime checked_out_time { get; set; }
        public int pollid { get; set; }
        public Nullable<short> browserNav { get; set; }
        public byte access { get; set; }
        public byte utaccess { get; set; }
        public string @params { get; set; }
        public long lft { get; set; }
        public long rgt { get; set; }
        public long home { get; set; }
        public int lang_id { get; set; }
    }
}
