//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCSV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jos_redirection
    {
        public int id { get; set; }
        public int cpt { get; set; }
        public int rank { get; set; }
        public string oldurl { get; set; }
        public string newurl { get; set; }
        public System.DateTime dateadd { get; set; }
    }
}
