//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCSV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jos_content
    {
        public string name_URL { get; set; }

        public string name_page { get; set; }

        public jos_content LEFT { get; set; }
        public jos_content RIGHT { get; set; }
        public jos_content MIDDLE { get; set; }
        public jos_content POS_1 { get; set; }
        public IEnumerable<jos_content> POS_1_LIST { get; set; }
        public jos_content POS_2 { get; set; }
        public IEnumerable<jos_content> POS_2_LIST { get; set; }

        public jos_content POS_3 { get; set; }
        public IEnumerable<jos_content> POS_3_LIST { get; set; }
        public jos_content POS_4 { get; set; }
        public IEnumerable<jos_content> POS_4_LIST { get; set; }
        public IEnumerable<jos_content> BANNER { get; set; }
        public IEnumerable<jos_content> NEWS { get; set; }
        public List<string> PAGING_LINK { get; set; }

        public jos_content FOOTER { get; set; }
        public jos_content TOP { get; set; }
        public IEnumerable<jos_menu> LEFT_MENU { get; set; }

        public IEnumerable<jos_contact> CONTACTS { get; set; }


        public long id { get; set; }
        public Nullable<int> old_cat_id { get; set; }
        public Nullable<int> old_id { get; set; }
        public string title { get; set; }
        public string alias { get; set; }
        public string title_alias { get; set; }
        public string introtext { get; set; }
        public string fulltext { get; set; }
        public Nullable<short> state { get; set; }
        public Nullable<long> sectionid { get; set; }
        public Nullable<long> mask { get; set; }
        public Nullable<long> catid { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public Nullable<long> created_by { get; set; }
        public string created_by_alias { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public Nullable<long> modified_by { get; set; }
        public Nullable<long> checked_out { get; set; }
        public Nullable<System.DateTime> checked_out_time { get; set; }
        public Nullable<System.DateTime> publish_up { get; set; }
        public Nullable<System.DateTime> publish_down { get; set; }
        public string images { get; set; }
        public string urls { get; set; }
        public string attribs { get; set; }
        public Nullable<long> version { get; set; }
        public Nullable<long> parentid { get; set; }
        public Nullable<int> ordering { get; set; }
        public string metakey { get; set; }
        public string metadesc { get; set; }
        public Nullable<long> access { get; set; }
        public Nullable<long> hits { get; set; }
        public string metadata { get; set; }
        public string position { get; set; }
        public int lang_id { get; set; }
    }
}
