//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCSV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jos_p_related
    {
        public long id { get; set; }
        public string title { get; set; }
        public Nullable<long> price { get; set; }
        public string detail { get; set; }
        public Nullable<short> published { get; set; }
        public long product { get; set; }
        public string image { get; set; }
        public Nullable<long> dateupdated { get; set; }
        public Nullable<long> ordering { get; set; }
    }
}
