//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCSV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jos_xmap_items
    {
        public string uid { get; set; }
        public int itemid { get; set; }
        public string view { get; set; }
        public int sitemap_id { get; set; }
        public string properties { get; set; }
    }
}
