//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCSV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jos_content
    {
        public long id { get; set; }
        public Nullable<int> old_cat_id { get; set; }
        public Nullable<int> old_id { get; set; }
        public string title { get; set; }
        public string alias { get; set; }
        public string title_alias { get; set; }
        public string introtext { get; set; }
        public string fulltext { get; set; }
        public Nullable<short> state { get; set; }
        public Nullable<long> sectionid { get; set; }
        public Nullable<long> mask { get; set; }
        public Nullable<long> catid { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public Nullable<long> created_by { get; set; }
        public string created_by_alias { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public Nullable<long> modified_by { get; set; }
        public Nullable<long> checked_out { get; set; }
        public Nullable<System.DateTime> checked_out_time { get; set; }
        public Nullable<System.DateTime> publish_up { get; set; }
        public Nullable<System.DateTime> publish_down { get; set; }
        public string images { get; set; }
        public string urls { get; set; }
        public string attribs { get; set; }
        public Nullable<long> version { get; set; }
        public Nullable<long> parentid { get; set; }
        public Nullable<int> ordering { get; set; }
        public string metakey { get; set; }
        public string metadesc { get; set; }
        public Nullable<long> access { get; set; }
        public Nullable<long> hits { get; set; }
        public string metadata { get; set; }
        public string position { get; set; }
        public int lang_id { get; set; }
        public string content_type { get; set; }
        public Nullable<long> comment_count { get; set; }
        public Nullable<long> approved_by { get; set; }
        public Nullable<long> publish_by { get; set; }
        public Nullable<System.DateTime> publish_time { get; set; }
    }
}
