//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCSV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jos_bannerclient
    {
        public int cid { get; set; }
        public string name { get; set; }
        public string contact { get; set; }
        public string email { get; set; }
        public string extrainfo { get; set; }
        public short checked_out { get; set; }
        public Nullable<System.TimeSpan> checked_out_time { get; set; }
        public string editor { get; set; }
    }
}
