//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCSV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jos_plugins
    {
        public int id { get; set; }
        public string name { get; set; }
        public string element { get; set; }
        public string folder { get; set; }
        public byte access { get; set; }
        public int ordering { get; set; }
        public short published { get; set; }
        public short iscore { get; set; }
        public short client_id { get; set; }
        public long checked_out { get; set; }
        public System.DateTime checked_out_time { get; set; }
        public string @params { get; set; }
    }
}
