//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCSV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tmp_jos_users
    {
        public int id { get; set; }
        public string name { get; set; }
        public string username { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string usertype { get; set; }
        public Nullable<bool> block { get; set; }
        public Nullable<short> sendEmail { get; set; }
        public Nullable<byte> gid { get; set; }
        public Nullable<System.DateTime> registerDate { get; set; }
        public Nullable<System.DateTime> lastvisitDate { get; set; }
        public string activation { get; set; }
        public string @params { get; set; }
    }
}
