//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCSV.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HCSV.Resources.GlobalResource", typeof(GlobalResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bảng giá áp dụng.
        /// </summary>
        public static string BANG_GIA {
            get {
                return ResourceManager.GetString("BANG_GIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bảng giá áp dụng.
        /// </summary>
        public static string BANG_GIA_AP_DUNG {
            get {
                return ResourceManager.GetString("BANG_GIA_AP_DUNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BẢNG GIÁ ÁP DỤNG HIỆN HÀNH
        ///    TẠI CÔNG TY TNHH DỊCH VỤ HÀNG HÓA TSN.
        /// </summary>
        public static string BANG_GIA_AP_DUNG_HIEN_HANH {
            get {
                return ResourceManager.GetString("BANG_GIA_AP_DUNG_HIEN_HANH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BẢNG GIÁ ÁP DỤNG HIỆN HÀNH TẠI CÔNG TY TNHH DỊCH VỤ HÀNG HÓA TSN.
        /// </summary>
        public static string BANG_GIA_HIEN_HANH {
            get {
                return ResourceManager.GetString("BANG_GIA_HIEN_HANH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo cáo phục vụ chuyến bay đến.
        /// </summary>
        public static string BAO_CAO_CHUYEN_BAY_DEN {
            get {
                return ResourceManager.GetString("BAO_CAO_CHUYEN_BAY_DEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bỏ qua.
        /// </summary>
        public static string BO_QUA {
            get {
                return ResourceManager.GetString("BO_QUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ca trưởng (CS - Import).
        /// </summary>
        public static string CA_TRUONG_CS_IMPORT {
            get {
                return ResourceManager.GetString("CA_TRUONG_CS_IMPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các hãng hàng không.
        /// </summary>
        public static string CAC_HANG_HANG_KHONG {
            get {
                return ResourceManager.GetString("CAC_HANG_HANG_KHONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các mức phụ thu.
        /// </summary>
        public static string CAC_MUC_PHU_THU {
            get {
                return ResourceManager.GetString("CAC_MUC_PHU_THU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHANGE PASSWORD.
        /// </summary>
        public static string CHANGE_PASSWORD {
            get {
                return ResourceManager.GetString("CHANGE_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn.
        /// </summary>
        public static string CHON {
            get {
                return ResourceManager.GetString("CHON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn ngày.
        /// </summary>
        public static string CHON_NGAY {
            get {
                return ResourceManager.GetString("CHON_NGAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chủ đề.
        /// </summary>
        public static string CHU_DE {
            get {
                return ResourceManager.GetString("CHU_DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyến bay.
        /// </summary>
        public static string CHUYEN_BAY {
            get {
                return ResourceManager.GetString("CHUYEN_BAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyến bay đã đặt chỗ.
        /// </summary>
        public static string CHUYEN_BAY_DA_DAT_CHO {
            get {
                return ResourceManager.GetString("CHUYEN_BAY_DA_DAT_CHO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã chất xếp.
        /// </summary>
        public static string DA_CHAT_XEP {
            get {
                return ResourceManager.GetString("DA_CHAT_XEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã gửi thư thông báo.
        /// </summary>
        public static string DA_GUI_THU_THONG_BAO {
            get {
                return ResourceManager.GetString("DA_GUI_THU_THONG_BAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã hoàn tất chất xếp.
        /// </summary>
        public static string DA_HOAN_TAT_SAP_XEP {
            get {
                return ResourceManager.GetString("DA_HOAN_TAT_SAP_XEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã lên Pre-Manifest chuyến bay.
        /// </summary>
        public static string DA_LEN_PRE_MANIFEST {
            get {
                return ResourceManager.GetString("DA_LEN_PRE_MANIFEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã qua soi chiếu.
        /// </summary>
        public static string DA_QUA_SOI_CHIEU {
            get {
                return ResourceManager.GetString("DA_QUA_SOI_CHIEU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã thông báo cho khách.
        /// </summary>
        public static string DA_THONG_BAO_CHO_KHACH {
            get {
                return ResourceManager.GetString("DA_THONG_BAO_CHO_KHACH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã tiếp nhận.
        /// </summary>
        public static string DA_TIEP_NHAN {
            get {
                return ResourceManager.GetString("DA_TIEP_NHAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã chất xếp trước máy soi.
        /// </summary>
        public static string DA_XEP_CHAT_TRUOC_MAY_SOI {
            get {
                return ResourceManager.GetString("DA_XEP_CHAT_TRUOC_MAY_SOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đại lý.
        /// </summary>
        public static string DAI_LY {
            get {
                return ResourceManager.GetString("DAI_LY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        public static string DANG_NHAP {
            get {
                return ResourceManager.GetString("DANG_NHAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dạng tệp.
        /// </summary>
        public static string DANG_TEP {
            get {
                return ResourceManager.GetString("DANG_TEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng xuất.
        /// </summary>
        public static string DANG_XUAT {
            get {
                return ResourceManager.GetString("DANG_XUAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách.
        /// </summary>
        public static string DANH_SACH {
            get {
                return ResourceManager.GetString("DANH_SACH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách hàng hóa chưa được giao nhận.
        /// </summary>
        public static string DANH_SACH_HANG_HOA_CHUA_DUOC_GIAO_NHAN {
            get {
                return ResourceManager.GetString("DANH_SACH_HANG_HOA_CHUA_DUOC_GIAO_NHAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DANH SÁCH MAWB.
        /// </summary>
        public static string DANH_SACH_MAWB {
            get {
                return ResourceManager.GetString("DANH_SACH_MAWB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đến.
        /// </summary>
        public static string DEN {
            get {
                return ResourceManager.GetString("DEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đến ngày.
        /// </summary>
        public static string DEN_NGAY {
            get {
                return ResourceManager.GetString("DEN_NGAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        public static string DIA_CHI {
            get {
                return ResourceManager.GetString("DIA_CHI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ mail.
        /// </summary>
        public static string DIA_CHI_EMAIL {
            get {
                return ResourceManager.GetString("DIA_CHI_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điểm đến.
        /// </summary>
        public static string DIEM_DEN {
            get {
                return ResourceManager.GetString("DIEM_DEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diễn giải.
        /// </summary>
        public static string DIEN_GIAI {
            get {
                return ResourceManager.GetString("DIEN_GIAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diễn giải tình trạng.
        /// </summary>
        public static string DIEN_GIAI_TINH_TRANG {
            get {
                return ResourceManager.GetString("DIEN_GIAI_TINH_TRANG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điện thoại.
        /// </summary>
        public static string DIEN_THOAI {
            get {
                return ResourceManager.GetString("DIEN_THOAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị tính.
        /// </summary>
        public static string DON_VI_TINH {
            get {
                return ResourceManager.GetString("DON_VI_TINH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đường dây nóng.
        /// </summary>
        public static string DUONG_DAY_NONG {
            get {
                return ResourceManager.GetString("DUONG_DAY_NONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản này đã bị khóa is blocked.
        /// </summary>
        public static string ERROR_MSG_BLOCKED_USER {
            get {
                return ResourceManager.GetString("ERROR_MSG_BLOCKED_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gõ sai thông tin Capcha.
        /// </summary>
        public static string ERROR_MSG_INVALID_CAPCHA {
            get {
                return ResourceManager.GetString("ERROR_MSG_INVALID_CAPCHA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gõ sai Username hoặc Password.
        /// </summary>
        public static string ERROR_MSG_INVALID_USER {
            get {
                return ResourceManager.GetString("ERROR_MSG_INVALID_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string FAX {
            get {
                return ResourceManager.GetString("FAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi chú.
        /// </summary>
        public static string GHI_CHU {
            get {
                return ResourceManager.GetString("GHI_CHU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIÁ CÁC LOẠI DỊCH VỤ KHÁC.
        /// </summary>
        public static string GIA_CAC_LOAI_DICH_VU_KHAC {
            get {
                return ResourceManager.GetString("GIA_CAC_LOAI_DICH_VU_KHAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá lao vụ cho hàng gửi lại kho.
        /// </summary>
        public static string GIA_LAO_VU_CHO_HANG_GUI_KHO {
            get {
                return ResourceManager.GetString("GIA_LAO_VU_CHO_HANG_GUI_KHO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá lao vụ cho hàng gửi lại kho.
        /// </summary>
        public static string GIA_LAO_VU_HANG_GUI_LAI_KHO {
            get {
                return ResourceManager.GetString("GIA_LAO_VU_HANG_GUI_LAI_KHO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIÁ LƯU KHO.
        /// </summary>
        public static string GIA_LUU_KHO {
            get {
                return ResourceManager.GetString("GIA_LUU_KHO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá lưu kho tại thời điểm.
        /// </summary>
        public static string GIA_LUU_KHO_TAI_THOI_DIEM {
            get {
                return ResourceManager.GetString("GIA_LUU_KHO_TAI_THOI_DIEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIÁ LƯU KHO TẠI THỜI ĐIỂM - HÀNG NHẬP.
        /// </summary>
        public static string GIA_LUU_KHO_TAI_THOI_DIEM_HANG_NHAP {
            get {
                return ResourceManager.GetString("GIA_LUU_KHO_TAI_THOI_DIEM_HANG_NHAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá lưu kho tại thời điểm-Hàng nhập.
        /// </summary>
        public static string GIA_LUU_KHO_TAI_THOI_DIEM_HANGNHAP {
            get {
                return ResourceManager.GetString("GIA_LUU_KHO_TAI_THOI_DIEM_HANGNHAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIÁ PHỤC VỤ.
        /// </summary>
        public static string GIA_PHUC_VU {
            get {
                return ResourceManager.GetString("GIA_PHUC_VU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giờ đến.
        /// </summary>
        public static string GIO_DEN {
            get {
                return ResourceManager.GetString("GIO_DEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giờ kết thúc.
        /// </summary>
        public static string GIO_KET_THUC {
            get {
                return ResourceManager.GetString("GIO_KET_THUC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to giờ:phút.
        /// </summary>
        public static string GIO_PHUT {
            get {
                return ResourceManager.GetString("GIO_PHUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gõ lại dòng chữ ở trên.
        /// </summary>
        public static string GO_CAPCHA {
            get {
                return ResourceManager.GetString("GO_CAPCHA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gõ lại mật khẩu mới.
        /// </summary>
        public static string GO_LAI_MAT_KHAU_MOI {
            get {
                return ResourceManager.GetString("GO_LAI_MAT_KHAU_MOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hải quan.
        /// </summary>
        public static string HAI_QUAN {
            get {
                return ResourceManager.GetString("HAI_QUAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hãng hàng không.
        /// </summary>
        public static string HANG_HANG_KHONG {
            get {
                return ResourceManager.GetString("HANG_HANG_KHONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hàng nhập kho từ ngày.
        /// </summary>
        public static string HANG_NHAP_KHO_TU_NGAY {
            get {
                return ResourceManager.GetString("HANG_NHAP_KHO_TU_NGAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hàng trong kho.
        /// </summary>
        public static string HANG_TRONG_KHO {
            get {
                return ResourceManager.GetString("HANG_TRONG_KHO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hãng vận chuyển.
        /// </summary>
        public static string HANG_VAN_CHUYEN {
            get {
                return ResourceManager.GetString("HANG_VAN_CHUYEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hàng xuất khẩu trong kho.
        /// </summary>
        public static string HANG_XUAT_KHAU_TRONG_KHO {
            get {
                return ResourceManager.GetString("HANG_XUAT_KHAU_TRONG_KHO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HAWB.
        /// </summary>
        public static string HAWB {
            get {
                return ResourceManager.GetString("HAWB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ tên.
        /// </summary>
        public static string HO_TEN {
            get {
                return ResourceManager.GetString("HO_TEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In báo cáo.
        /// </summary>
        public static string IN_BAO_CAO {
            get {
                return ResourceManager.GetString("IN_BAO_CAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In báo cáo phục vụ chuyến bay đến.
        /// </summary>
        public static string IN_BAO_CAO_CHUYEN_BAY_DEN {
            get {
                return ResourceManager.GetString("IN_BAO_CAO_CHUYEN_BAY_DEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In báo cáo tình trạng tài liệu và hàng hoá.
        /// </summary>
        public static string IN_BAO_CAO_TINH_TRANG_TAI_LIEU_VA_HANG_HOA {
            get {
                return ResourceManager.GetString("IN_BAO_CAO_TINH_TRANG_TAI_LIEU_VA_HANG_HOA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In.
        /// </summary>
        public static string IN_MAN_HINH {
            get {
                return ResourceManager.GetString("IN_MAN_HINH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không vận đơn.
        /// </summary>
        public static string KHONG_VAN_DON {
            get {
                return ResourceManager.GetString("KHONG_VAN_DON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SỐ KHÔNG VẬN ĐƠN KHÔNG TỒN TẠI.
        /// </summary>
        public static string KHONG_VAN_DON_KHONG_TON_TAI {
            get {
                return ResourceManager.GetString("KHONG_VAN_DON_KHONG_TON_TAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiểm hàng (OA - Checker).
        /// </summary>
        public static string KIEM_HANG_OA_CHECKER {
            get {
                return ResourceManager.GetString("KIEM_HANG_OA_CHECKER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Làm mới.
        /// </summary>
        public static string LAM_MOI {
            get {
                return ResourceManager.GetString("LAM_MOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên kết nhanh.
        /// </summary>
        public static string LIEN_KET_NHANH {
            get {
                return ResourceManager.GetString("LIEN_KET_NHANH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại.
        /// </summary>
        public static string LOAI {
            get {
                return ResourceManager.GetString("LOAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại hàng.
        /// </summary>
        public static string LOAI_HANG {
            get {
                return ResourceManager.GetString("LOAI_HANG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại lưu kho.
        /// </summary>
        public static string LOAI_LUU_KHO {
            get {
                return ResourceManager.GetString("LOAI_LUU_KHO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại phục vụ.
        /// </summary>
        public static string LOAI_PHUC_VU {
            get {
                return ResourceManager.GetString("LOAI_PHUC_VU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        public static string MAT_KHAU {
            get {
                return ResourceManager.GetString("MAT_KHAU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu cũ.
        /// </summary>
        public static string MAT_KHAU_CU {
            get {
                return ResourceManager.GetString("MAT_KHAU_CU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu mới.
        /// </summary>
        public static string MAT_KHAU_MOI {
            get {
                return ResourceManager.GetString("MAT_KHAU_MOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAWB.
        /// </summary>
        public static string MAWB {
            get {
                return ResourceManager.GetString("MAWB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miễn phí.
        /// </summary>
        public static string MIEN_PHI {
            get {
                return ResourceManager.GetString("MIEN_PHI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MỨC THU (VND).
        /// </summary>
        public static string MUC_THU {
            get {
                return ResourceManager.GetString("MUC_THU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày.
        /// </summary>
        public static string NGAY {
            get {
                return ResourceManager.GetString("NGAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày giờ in báo cáo.
        /// </summary>
        public static string NGAY_GIO_IN_BAO_CAO {
            get {
                return ResourceManager.GetString("NGAY_GIO_IN_BAO_CAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chủ nhật, Ngày lễ.
        /// </summary>
        public static string NGAY_LE {
            get {
                return ResourceManager.GetString("NGAY_LE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ 00:00 đến 23:59 các ngày Chủ nhật, ngày nghĩ Lễ, Tết, ngày nghỉ bù của Lễ, Tết theo quy định của nhà nước.
        /// </summary>
        public static string NGAY_NGHI_LE_TET {
            get {
                return ResourceManager.GetString("NGAY_NGHI_LE_TET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày nhập kho.
        /// </summary>
        public static string NGAY_NHAP_KHO {
            get {
                return ResourceManager.GetString("NGAY_NHAP_KHO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày xuất kho.
        /// </summary>
        public static string NGAY_XUAT_KHO {
            get {
                return ResourceManager.GetString("NGAY_XUAT_KHO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người gửi.
        /// </summary>
        public static string NGUOI_GOI {
            get {
                return ResourceManager.GetString("NGUOI_GOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người gửi.
        /// </summary>
        public static string NGUOI_GUI {
            get {
                return ResourceManager.GetString("NGUOI_GUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người nhận.
        /// </summary>
        public static string NGUOI_NHAN {
            get {
                return ResourceManager.GetString("NGUOI_NHAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người nhận trực tiếp.
        /// </summary>
        public static string NGUOI_NHAN_TT {
            get {
                return ResourceManager.GetString("NGUOI_NHAN_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên / bộ phận.
        /// </summary>
        public static string NHAN_VIEN_BO_PHAN {
            get {
                return ResourceManager.GetString("NHAN_VIEN_BO_PHAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hãy nhập số và ngày của chuyến bay để tiếp tục..
        /// </summary>
        public static string NHAP_SO_NGAY_CHUYEN_BAY {
            get {
                return ResourceManager.GetString("NHAP_SO_NGAY_CHUYEN_BAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nơi đến.
        /// </summary>
        public static string NOI_DEN {
            get {
                return ResourceManager.GetString("NOI_DEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung.
        /// </summary>
        public static string NOI_DUNG {
            get {
                return ResourceManager.GetString("NOI_DUNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NỘI DUNG CÁC KHOẢN THU.
        /// </summary>
        public static string NOI_DUNG_CAC_KHOAN_THU {
            get {
                return ResourceManager.GetString("NOI_DUNG_CAC_KHOAN_THU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nơi xuất phát.
        /// </summary>
        public static string NOI_XUAT_PHAT {
            get {
                return ResourceManager.GetString("NOI_XUAT_PHAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORG.
        /// </summary>
        public static string ORG {
            get {
                return ResourceManager.GetString("ORG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin khác.
        /// </summary>
        public static string OTHER_NEWS {
            get {
                return ResourceManager.GetString("OTHER_NEWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phần A.
        /// </summary>
        public static string PHAN_A {
            get {
                return ResourceManager.GetString("PHAN_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phần B.
        /// </summary>
        public static string PHAN_B {
            get {
                return ResourceManager.GetString("PHAN_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phần C.
        /// </summary>
        public static string PHAN_C {
            get {
                return ResourceManager.GetString("PHAN_C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiếu thông báo hàng đến.
        /// </summary>
        public static string PHIEU_THONG_BAO_HANG_DEN {
            get {
                return ResourceManager.GetString("PHIEU_THONG_BAO_HANG_DEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiếu thông báo tình trạng tài liệu.
        /// </summary>
        public static string PHIEU_THONG_BAO_TINH_TRANG_TAI_LIEU {
            get {
                return ResourceManager.GetString("PHIEU_THONG_BAO_TINH_TRANG_TAI_LIEU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHỤ THU GIÁ LAO VỤ NGOÀI GIỜ.
        /// </summary>
        public static string PHU_THU_GIA_LAO_VU_NGOAI_GIO {
            get {
                return ResourceManager.GetString("PHU_THU_GIA_LAO_VU_NGOAI_GIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quy đổi.
        /// </summary>
        public static string QUY_DOI {
            get {
                return ResourceManager.GetString("QUY_DOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số.
        /// </summary>
        public static string SO {
            get {
                return ResourceManager.GetString("SO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số hiệu.
        /// </summary>
        public static string SO_HIEU {
            get {
                return ResourceManager.GetString("SO_HIEU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số hiệu chuyến bay.
        /// </summary>
        public static string SO_HIEU_CHUYEN_BAY {
            get {
                return ResourceManager.GetString("SO_HIEU_CHUYEN_BAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số không vận đơn.
        /// </summary>
        public static string SO_KHONG_VAN_DON {
            get {
                return ResourceManager.GetString("SO_KHONG_VAN_DON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số không vận đơn.
        /// </summary>
        public static string SO_KHONG_VD {
            get {
                return ResourceManager.GetString("SO_KHONG_VD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số kiện.
        /// </summary>
        public static string SO_KIEN {
            get {
                return ResourceManager.GetString("SO_KIEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số kiện hàng.
        /// </summary>
        public static string SO_KIEN_HANG {
            get {
                return ResourceManager.GetString("SO_KIEN_HANG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số ngày tính phí.
        /// </summary>
        public static string SO_NGAY_TINH_PHI {
            get {
                return ResourceManager.GetString("SO_NGAY_TINH_PHI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số nội bộ.
        /// </summary>
        public static string SO_NOI_BO {
            get {
                return ResourceManager.GetString("SO_NOI_BO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số trang MNF.
        /// </summary>
        public static string SO_TRANG_MNF {
            get {
                return ResourceManager.GetString("SO_TRANG_MNF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STT.
        /// </summary>
        public static string STT {
            get {
                return ResourceManager.GetString("STT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sự khác biệt của bản danh sách hàng hóa.
        /// </summary>
        public static string SU_KHAC_BIET_DANH_SACH_HANG_HOA {
            get {
                return ResourceManager.GetString("SU_KHAC_BIET_DANH_SACH_HANG_HOA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sự khác biệt của không vận đơn.
        /// </summary>
        public static string SU_KHAC_BIET_KHONG_VAN_DON {
            get {
                return ResourceManager.GetString("SU_KHAC_BIET_KHONG_VAN_DON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sự khác biệt về tình trạng hàng hóa.
        /// </summary>
        public static string SU_KHAC_BIET_TINH_TRANG_HANG_HOA {
            get {
                return ResourceManager.GetString("SU_KHAC_BIET_TINH_TRANG_HANG_HOA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sứ mệnh, Tầm nhìn, Giá trị cốt lõi.
        /// </summary>
        public static string SU_MENH_TAM_NHIN_GTCL {
            get {
                return ResourceManager.GetString("SU_MENH_TAM_NHIN_GTCL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài liệu.
        /// </summary>
        public static string TAI_LIEU {
            get {
                return ResourceManager.GetString("TAI_LIEU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài liệu kèm HAWB.
        /// </summary>
        public static string TAI_LIEU_KEM_HAWB {
            get {
                return ResourceManager.GetString("TAI_LIEU_KEM_HAWB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài liệu (OA - Document).
        /// </summary>
        public static string TAI_LIEU_OA_DOC {
            get {
                return ResourceManager.GetString("TAI_LIEU_OA_DOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tải về.
        /// </summary>
        public static string TAI_VE {
            get {
                return ResourceManager.GetString("TAI_VE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên.
        /// </summary>
        public static string TEN {
            get {
                return ResourceManager.GetString("TEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập.
        /// </summary>
        public static string TEN_DANG_NHAP {
            get {
                return ResourceManager.GetString("TEN_DANG_NHAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên người dùng.
        /// </summary>
        public static string TEN_NGUOI_DUNG {
            get {
                return ResourceManager.GetString("TEN_NGUOI_DUNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thay đổi mật khẩu.
        /// </summary>
        public static string THAY_DOI_MAT_KHAU {
            get {
                return ResourceManager.GetString("THAY_DOI_MAT_KHAU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thể tích.
        /// </summary>
        public static string THE_TICH {
            get {
                return ResourceManager.GetString("THE_TICH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thoát.
        /// </summary>
        public static string THOAT {
            get {
                return ResourceManager.GetString("THOAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thống kê.
        /// </summary>
        public static string THONG_KE {
            get {
                return ResourceManager.GetString("THONG_KE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin bất thường.
        /// </summary>
        public static string THONG_TIN_BAT_THUONG {
            get {
                return ResourceManager.GetString("THONG_TIN_BAT_THUONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin giá cả.
        /// </summary>
        public static string THONG_TIN_GIA_CA {
            get {
                return ResourceManager.GetString("THONG_TIN_GIA_CA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin hàng hóa.
        /// </summary>
        public static string THONG_TIN_HANG_HOA {
            get {
                return ResourceManager.GetString("THONG_TIN_HANG_HOA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin hàng hóa nhập khẩu.
        /// </summary>
        public static string THONG_TIN_HANG_HOA_NHAP_KHAU {
            get {
                return ResourceManager.GetString("THONG_TIN_HANG_HOA_NHAP_KHAU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin về phục vụ hàng hóa.
        /// </summary>
        public static string THONG_TIN_PHUC_VU_HANG_HOA {
            get {
                return ResourceManager.GetString("THONG_TIN_PHUC_VU_HANG_HOA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin vận chuyển.
        /// </summary>
        public static string THONG_TIN_VAN_CHUYEN {
            get {
                return ResourceManager.GetString("THONG_TIN_VAN_CHUYEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thực tế.
        /// </summary>
        public static string THUC_TE {
            get {
                return ResourceManager.GetString("THUC_TE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thuế.
        /// </summary>
        public static string THUE {
            get {
                return ResourceManager.GetString("THUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tra cứu vận đơn.
        /// </summary>
        public static string TIM_KIEM_VAN_DON {
            get {
                return ResourceManager.GetString("TIM_KIEM_VAN_DON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span style=&quot;color:#000000&quot;&gt;Tin &lt;/span&gt;
        ///    &lt;span style=&quot;color:#ffa400&quot;&gt;chuyên ngành&lt;/span&gt;.
        /// </summary>
        public static string TIN_CHUYEN_NGANH {
            get {
                return ResourceManager.GetString("TIN_CHUYEN_NGANH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span style=&quot;color:#000000&quot;&gt;Tin &lt;/span&gt;
        ///    &lt;span style=&quot;color:#ffa400&quot;&gt;dành cho khách hàng&lt;/span&gt;.
        /// </summary>
        public static string TIN_DANH_CHO_KH {
            get {
                return ResourceManager.GetString("TIN_DANH_CHO_KH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin mới.
        /// </summary>
        public static string TIN_MOI {
            get {
                return ResourceManager.GetString("TIN_MOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span style=&quot;color:#000000&quot;&gt;Tin &lt;/span&gt;
        ///    &lt;span style=&quot;color:#ffa400&quot;&gt;TCS&lt;/span&gt;.
        /// </summary>
        public static string TIN_TCS {
            get {
                return ResourceManager.GetString("TIN_TCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tính chất khác biệt/ xử lý.
        /// </summary>
        public static string TINH_CHAT_KHAC_BIET_XU_LY {
            get {
                return ResourceManager.GetString("TINH_CHAT_KHAC_BIET_XU_LY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tình trạng.
        /// </summary>
        public static string TINH_TRANG {
            get {
                return ResourceManager.GetString("TINH_TRANG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tình trạng hàng hoá xuất khẩu.
        /// </summary>
        public static string TINH_TRANG_HANG_HOA_XUAT_KHAU {
            get {
                return ResourceManager.GetString("TINH_TRANG_HANG_HOA_XUAT_KHAU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TÌNH TRẠNG HÀNG NHẬP.
        /// </summary>
        public static string TINH_TRANG_HANG_NHAP {
            get {
                return ResourceManager.GetString("TINH_TRANG_HANG_NHAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng cộng.
        /// </summary>
        public static string TONG_CONG {
            get {
                return ResourceManager.GetString("TONG_CONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng số HAWB.
        /// </summary>
        public static string TONG_SO_HAWB {
            get {
                return ResourceManager.GetString("TONG_SO_HAWB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng số kiện.
        /// </summary>
        public static string TONG_SO_KIEN {
            get {
                return ResourceManager.GetString("TONG_SO_KIEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        public static string TRANG_THAI {
            get {
                return ResourceManager.GetString("TRANG_THAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trở lại.
        /// </summary>
        public static string TRO_LAI {
            get {
                return ResourceManager.GetString("TRO_LAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trọng lượng.
        /// </summary>
        public static string TRONG_LUONG {
            get {
                return ResourceManager.GetString("TRONG_LUONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trọng lượng cân lại (nếu có).
        /// </summary>
        public static string TRONG_LUONG_CAN_LAI {
            get {
                return ResourceManager.GetString("TRONG_LUONG_CAN_LAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ.
        /// </summary>
        public static string TU {
            get {
                return ResourceManager.GetString("TU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ 17:00 đến 21:59 từ thứ Hai đến thứ Bảy.
        /// </summary>
        public static string TU_1700_2159_THU2_THU7 {
            get {
                return ResourceManager.GetString("TU_1700_2159_THU2_THU7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Từ 22:00 đến 05:59 sáng hôm sau các ngày từ thứ Hai đến thứ Sáu.
        /// </summary>
        public static string TU_2200_0559_THU2_THU6 {
            get {
                return ResourceManager.GetString("TU_2200_0559_THU2_THU6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Từ 22:00 đến 23:59 thứ Bảy và 00:00 đến 05:59 thứ Hai.
        /// </summary>
        public static string TU_2200_2359_THU7_VA_0000_0559_THU2 {
            get {
                return ResourceManager.GetString("TU_2200_2359_THU7_VA_0000_0559_THU2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ ngày:.
        /// </summary>
        public static string TU_NGAY {
            get {
                return ResourceManager.GetString("TU_NGAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng điền thông tin đăng nhập.
        /// </summary>
        public static string VUI_LONG_DIEN_THONG_TIN_DANG_NHAP {
            get {
                return ResourceManager.GetString("VUI_LONG_DIEN_THONG_TIN_DANG_NHAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận.
        /// </summary>
        public static string XAC_NHAN {
            get {
                return ResourceManager.GetString("XAC_NHAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Để xem thông tin KVĐ phụ hoặc in báo cáo - (Dùng cho Đại lý hoặc Airlines).
        /// </summary>
        public static string XEM_THONG_TIN_KVD {
            get {
                return ResourceManager.GetString("XEM_THONG_TIN_KVD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem tiếp.
        /// </summary>
        public static string XEM_TIEP {
            get {
                return ResourceManager.GetString("XEM_TIEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin mời nhập Không vận đơn.
        /// </summary>
        public static string XIN_MOI_NHAP_KVD {
            get {
                return ResourceManager.GetString("XIN_MOI_NHAP_KVD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm.
        /// </summary>
        public static string YEAR {
            get {
                return ResourceManager.GetString("YEAR", resourceCulture);
            }
        }
    }
}
